[device]
part = "GW5AST-LV138PG484AC1/I0"
version = "B"

[files]
cst = "src/hdmi.cst"
sdc = "src/hdmi.sdc"
verilog = [
"src/design.sv",
"src/dvi-tx/dvi_tx_clk_drv.v",
"src/dvi-tx/dvi_tx_tmds_enc.v",
"src/dvi-tx/dvi_tx_tmds_phy.v",
"src/dvi-tx/dvi_tx_top.v",
# "src/gowin_pll_old/gowin_pll.v",
"src/gowin_pll/gowin_pll.v",
"src/gowin_pll/gowin_pll_mod.v",
"src/pll_init.v",
# "src/top.v",
# "src/video-misc/test_pattern_gen.v",
"target/src/top.sv",
"target/src/me.sv",
"src/video-misc/video_timing_ctrl.v"
]

[options]
verilog_std = "sysv2017"
top_module = "ctech_top"
place_option = 3
route_option = 2
bit_compress = true
cst_warn_to_error = true
rpt_auto_place_io_info = true
# use_sspi_as_gpio = true
# use_mspi_as_gpio = true
# use_cpu_as_gpio = true
